name: flutter_local_notifications_example
description: Demonstrates how to use the flutter_local_notifications plugin.
publish_to: none

dependencies:
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  flutter:
    sdk: flutter

  
  http: ^0.13.4
  image: ^3.0.8
  path_provider: ^2.0.0
  flutter_local_notifications: ^16.3.0
  flutter_timezone: ^1.0.4
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

# The following overrides exist to ensure the example app builds with the latest code
# of these packages as part of CI


flutter:
  uses-material-design: true
  assets:
    - icons/
    - sound/

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

analyzer:
  plugins:
    - custom_lint
